name: chat_app_ba
description: "A new Flutter project."


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8


  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  # google_sign_in: ^7.2.0
  google_sign_in: ^6.3.0


  # firebase_core: ^3.3.0
  # firebase_auth: ^5.3.1
  # google_sign_in: ^6.2.1

  cloud_firestore: ^6.0.3
  cached_network_image: ^3.4.1
  firebase_messaging: ^16.0.3
  firebase_storage: ^13.0.3
  image_picker: ^1.2.0
  lottie: ^3.3.1
  google_generative_ai: ^0.4.7
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

#   flutter_launcher_icons: ^0.14.4

# flutter_launcher_icons:
#   android: "ic_launcher"
#   ios: true
#   image_path: "images/logo_ba.png"
#   min_sdk_android: 21 
#   remove_alpha_ios: true
#   web:
#     generate: true
#     image_path: "images/logo_ba.png"
#     background_color: "#hexcode"
#     theme_color: "#hexcode"
#   windows:
#     generate: true
#     image_path: "images/logo_ba.png"
#     icon_size: 48 # min:48, max:256, default: 48


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
