// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8lxxdSAdMwQWP9G1Euv-nMRGKIw_vAx4',
    appId: '1:99546875749:web:f8e1c1315d96f6b053438c',
    messagingSenderId: '99546875749',
    projectId: 'chatappba-252d1',
    authDomain: 'chatappba-252d1.firebaseapp.com',
    storageBucket: 'chatappba-252d1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_REGk_PgJO2aZBWHZoDezXDqtjGK-C6M',
    appId: '1:99546875749:android:f430bfcd84e3c8ad53438c',
    messagingSenderId: '99546875749',
    projectId: 'chatappba-252d1',
    storageBucket: 'chatappba-252d1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8lxxdSAdMwQWP9G1Euv-nMRGKIw_vAx4',
    appId: '1:99546875749:web:4ca9d17ac764db1953438c',
    messagingSenderId: '99546875749',
    projectId: 'chatappba-252d1',
    authDomain: 'chatappba-252d1.firebaseapp.com',
    storageBucket: 'chatappba-252d1.firebasestorage.app',
  );

}